language: ruby
rvm:
- 2.5.3
before_install:
- gem install bundler
services:
- postgresql
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: VEf+MD+7YfLIOhiuBIcXk7c/DCC+ZuSRFNjIO4oWE5zyr8JqEShuB7ujLts7+sAk1vraUGmaKINSW1OHjKoh/UwpZvyHeEibfNPNDp2v0uUrt+qRAD3U6MXajm2X502q5Qyqwaa6jPxE24x/zpGchySNb5rgvE+fbAbWRKOt40w5ZSbLihcBBI6sm0t9N7fZ3c7t7FaU554PuMqtv+mz1pHzHIIwlYrk40sYelOGyovFf9ny8pBIPuM+tf1zv+6QeIJqSJB2PHUpCtirPVuMoeecWVSDD/Nupxtw1fEtQ8sHOPJvGPJb3r/Rk0Cm2ZgETVroQNptMlqcoBJipkQZZ3QdJabd+YNkeK2AdMblsttGqkllUVhaMODFv4IMdddHk4Rsk8kIgCtmunfqmGLcBuFO7o9r9wC3mvgb8Vj4Hb1UtCsDqpLBtiT2SfwxXdwH6pfobokBR07jnL3cvlbZYWLPoL93bBK6CkMQMMWmSSPoZHFMbWOpQtIMdtfotwv63GB3hOtik/KKrecWRnIEWghxn4O9Bw1p9qTJRhsmIAq+M2z5Oifn7jY45qvqfzU8ItOICuUunK54/S8xIMX2lxqsuSUMQ/w6hy0uHFHlj1dc9tEaiFeajYM4KMhpuV8Xb72vNgu0aLm+Ph23ElHH6qk6pi9LOADEJIBp5Uxs/E8=
  app: mighty-meadow-25750
  on:
    repo: mikez321/rails_engine
  skip_cleanup: 'true'
