language: ruby
rvm:
- 2.5.3
before_install:
- gem install bundler
services:
- postgresql
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: IFKi+0C9qA3q113EEarkjJ5jpmVNUHFfwcVqf/FkNPfdJX+EdWD9nfuSVvrxeyc30wa1YE/t2Aue0xM4qayj9Si+RlA36W6fHovwpVKRfS9oEErDprYTY1c4zXaFU/BoeTty0caZtu/HmNDdd3Ajf6L/XNRSwhyYR5JxlshHSnk0y7MhPrxD/zosiW4AQigOWUCgf/3PXLyl9heUgs0mCgRGvBsjU89geKRjgBaWH40KxzzsZ8FTNj+3ovGg+go8kGPwB1UHY7TXpwapVTCaID7WifdfjHwIb2L887ERNFMzqL2ycthkDkZVbExcxm51HLuxHzVRRIv1y1wlHE+QdzmNFmkORceLr66Wx2a9P6/KwWRavIHGkdfrvOy/fxMy+/oWghJTPJiy8WUMvBhMfUUMCFQQHTSyPKX0cLKj7eTzJD10kTqTcO/s4i3k55xpp4RC38YeZggXIxqk7qv2bcXrrvQ2BsJjrEGQChNsueplInZa/qkKP2zG7T4dKpZ7zfFpRdvLmRemPLEIYu1Ne24zIRE061fYonyIF3eEKa8/nNnDlkGdCbmXYJ54ZTbjiVy7WxW1mbLEs9tSqpBzXQbFjPud6ElEvO7P0iHZq8YyPrbVKQah1x1AaWUUj6cHVFen8BoBu18BFsIxM28NC87+JxDtf0VJkVm4ia4rbDU=
  app: mighty-meadow-25750
  on:
    repo: mikez321/rails_engine
  skip_cleanup: 'true'
