language: ruby
rvm:
- 2.5.3
before_install:
- gem install bundler
services:
- postgresql
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: YkTYT5ioEdB3eEUV1KnYnjhQd5NW9tMfXqW4QJW0t9lSoO8BGpjnJPnwDffth63Qyoc19wQdViRaHnMhrR0/BtqdoY/lidt2HURJHG7tiMxblROTH/2yYNHkrcBDCXyXH9+cAy/bLOEnnDxV1y/qrtfLw1zE51Y8b2smIgm8VzvJMNxoZZSC/9VvQsX8sDMCMpH1U8+wWTUFGRIff6Zz6nDPJWW1xvc4PheVYtgUpxuPkHN0ftx2lYfLPotJMQkU3pzB2NhiZ9AVIoc+sDDWbYoXLCM03b1LUNzL7iWlVXG8QALilRgo2beVkRaSXR0mx9MAkWJ4i3Z+Z8DHfh7z+ZWGwhpTnBE9WuFCcZf8nxjCaIzZms0BwKMJ3HVMtgTs+xGWNp6ew/xouG1CYqRUM3j0EH4oYMMiXha8y+ATV0pnrmquCMxoo4733qUbdtVuVupEixj6NSfg2qn80G+u3xwiiBLJB8wkC3KySPHBLRHDhvbTCMcXcqn61getmLxzFI6BAOY8L9V6lhaQgNjDbiMrC1VKk/g3Ze390KUcCJRhq3IsVnLETU1AFrChDPHj/c7MEfT5pi4JXy8tLgWKjF2AuUP/nlbLgSWlU7Zc+1Nd0QpiMJwvswp1FXFlaySEo2+bniEAHtJ/I00bvEj/XljPR/Q1sqi5inR+T1CBADA=
notifications:
  email: false
